PROGRAM BUFFER_OVERFLOW
      CHARACTER*5 STRING1
      CHARACTER*20 STRING2
      STRING1 = 'HELLO'
      STRING2 = 'THIS IS A LONG STRING THAT WILL OVERFLOW THE BUFFER'
      PRINT*, STRING1
      PRINT*, STRING2
      END